# Setup
title:               SPARSEDATA.ML
tagline:             'thinking machines'
description:         'Blog of Il Jae Lee.'
baseurl:             ''
paginate:            5
permalink:           pretty

# Liquid latex
liquid_latex:
  density:           150
  usepackages:       amsmath,amssymb,mathtools,dot2texi,tikz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
