# Setup
title:               Explorations in ML
tagline:             'thinking machines'
description:         'A blog on machine learning, probabilistic methods and intelligent systems.'
url:                 https://tensor.blog
baseurl:             ''
paginate:            5
permalink:           pretty
destination:         docs/

# Liquid latex
liquid_latex:
  density:           150
  usepackages:       amsmath,amssymb,mathtools,dot2texi,tikz

# About/contact
author:
  name:              Il Jae Lee
  url:               https://tensor.blog
  email:             agiantwhale@gmail.com

# Assets
sass:
  style:             compressed

assets:
  compression: true
  gzip: true
  sources:
    - _assets/

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-61575797-6
