# Setup
title:               SPARSEDATA.ML
tagline:             'thinking machines'
description:         'Blog of Il Jae Lee.'
url:                 http://sparsedata.ml
baseurl:             ''
paginate:            5
permalink:           pretty

# Liquid latex
liquid_latex:
  density:           150
  usepackages:       amsmath,amssymb,mathtools,dot2texi,tikz

# About/contact
author:
  name:              Il Jae Lee
  url:               https://sparsedata.ml
  email:             agiantwhale@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
